version: '3.9'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - task-managment-volume:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: task-managment
volumes:
  task-managment-volume:
